packages/ui/components/Label.tsx
packages/ui/components/LabetText.tsx

- close #18
Label 및 LabelText 공통 컴포넌트를 구현했습니다.
labelTitle: label에 들어갈 텍스트입니다
type: 배경색 타입입니다. 녹색, 주황색, 노란색, 빨간색의 타입이 있으며 기본값은 녹색으로 설정했습니다. 
``` ts
const LABEL_BACKGROUND_COLOR = {
GREEN: 'green.300',
ORANGE: 'orange.400',
YELLOW: 'yellow.300',
RED: 'red.400',
} as const;
export type LabelProps = {
labelTitle: string;
type?: keyof typeof LABEL_BACKGROUND_COLOR;
};
```
labelTitle,type은 Label에 넣기 위해 입력해야 합니다
content : label 옆에 넣을 텍스트입니다
``` ts
type LabelTextProps = { content: string } & LabelProps;
```
types 폴더는 현재 만들면 안될거 같아서 일단은 한 파일 내에 넣어놓았고 추후에 타입 분리 예정입니다.

feat: Label, LabelText 공통 컴포넌트

---

packages/ui/components/ProfileInfo.tsx

- close #22 
profileInfo 컴포넌트를 구현했습니다
imageUrl : 이미지 src 주소
name: 프로필 사용자의 이름
email: 프로필 사용자의 이메일
address: 프로필 사용자의 주소 ( 보호소프로필에서 사용합니다)
phoneNumber: 프로필 사용자의 핸드폰번호 (봉사자 프로필에서 사용합니다)
children: 온도 라벨 입니다.
```ts
type ProfileInfoProps = {
imageUrl?: string;
name: string;
email: string;
address?: string;
phoneNumber?: string;
children?: React.ReactNode;
};
```
프로필 이미지가 없는 사용자의 경우 차크라에서 제공하는 default 이미지를 보여줍니다.
피그마에서 보호소 프로필에서 주소가 있는 경우도 있고 없는 경우도 있습니다. 
디자인에서 빠진건지 의도적으로 디자인된 작업인지 궁금합니다.

feat(ui): profileInfo 컴포넌트 제작

---

packages/shared/layout/Header/DefaultHeader/index.tsx
packages/shared/layout/Header/DetailHeader/index.tsx
packages/shared/layout/Header/SearchHeader/index.tsx
packages/shared/layout/index.tsx
packages/shared/theme/index.ts

- close #78 
- 공통 레이아웃의 contents 부분에 overflowY scroll 속성을 추가했습니다
- 공통 레이아웃 header 컴포넌트에 zIndex 를 10씩 추가했습니다
- overscroll-behavior 을 none 으로 변경하여 default scroll 이벤트를 막았습니다

bug: 공통 레이아웃 컴포넌트 UI 깨짐 현상 수정

---

apps/shelter/src/pages/signup/index.tsx
apps/volunteer/src/pages/signup/index.tsx
packages/shared/components/RadioGroup.tsx
packages/shared/hooks/useRadioGroup.ts

- close #69 
* [feat(shared): useRadioGroup 훅 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/94db7597583ddc5d341df68cd49e9e4211a8f656)
* [feat(shared): RadioGroup 컴포넌트 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/770eda54764358f7616c1d2c8abf59993e72ef75)
* [feat(shelter): SignupPage 컴포넌트 UI 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/c67238198e72cc783eaa6bf9b927c704c5d28be4)
* [feat(volunteer): SignupPage 컴포넌트 UI 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/dfb13ec4f56f9b3f06e1792ffa80c564a6f3d651)
```tsx
import RadioGroup from 'shared/components/RadioGroup';
import useRadioGroup from 'shared/hooks/useRadioGroup';
type GenderValue = 'FEMALE' | 'MALE';
type GenderText = '여성' | '남성';
export default function SignupPage() {
const …
```

feat: 보호소앱과 봉사자앱의 회원가입 페이지의 UI, useRadioGroup 훅, RadioGroup 컴포넌트 추가

---

packages/shared/layout/index.tsx

- close #94 
`BottomNavBar` 가 없는 경우에는 margin bottom 이 필요하지 않아서,
`BottomNavBar` 가 있는 경우에는 각 페이지에 margin bottom 을 추가해주어야 할 것 같습니다.

design(shared): 공통 레이아웃 컴포넌트의 margin bottom 제거

---

apps/shelter/src/apis/shelter.ts
apps/shelter/src/mocks/browser.ts
apps/shelter/src/mocks/handlers/shelter.ts
apps/shelter/src/pages/my/_hooks/useMyPage.ts
apps/shelter/src/pages/my/index.tsx
apps/shelter/src/types/apis/shetler.ts
packages/shared/apis/axiosInstance.ts

- close #79 
- 보호소 프로필 조회 기능
- 보호소 프로필 상세주소 공개/비공개 토글
- `axiosInstance` 의 response `interceptor` 가 `response.data` 를 반환하므로, get, post, delete, patch 함수의 return 타입이 `Promise<Response>`가 되어야 하나, 타입스크립트에서 `Promise<AxiosResponse<Response>>` 로 자동 타입 추론되어 타입 에러가 발생
->  이를 해결하기 위해 return 문에 타입 단언을 추가했습니다.
-> 팀 논의 후, axios response interceptor 제거 및 AxiosResponse 에서 data 만 뽑아서 반환하는 기능 제거하기로 결정
- api 함수는 함수 뒤에 API postfix 를 추가하여, 함수명 중복을 피하고, API 함수임을 명확하게 드러내고자 했습니다.

feat(shelter): 보호소 마이페이지 msw 연결

---

apps/shelter/src/apis/auth.ts
apps/shelter/src/types/apis/auth.ts
apps/volunteer/src/apis/auth.ts
apps/volunteer/src/types/apis/auth.ts
packages/shared/types/apis/auth.ts
packages/shared/types/apis/error.ts

- close #117 
* [refactor(shared): error 관련 response data type명 명확하게 변경](https://github.com/Anifriends/Anifriends-Frontend/commit/e1181561b2a0ee3f314b6ffa8b5813bcf115bfad)
* [refactor(shared, shelter, volunteer): auth 관련 type명 명확하게 변경](https://github.com/Anifriends/Anifriends-Frontend/commit/262f1c2f4e84d04604b405803f9cb8ef5e5ada09)
* [refactor(shelter, volunteer): auth 관련 api 함수들에서 error 제거](https://github.com/Anifriends/Anifriends-Frontend/commit/3084089a8b1beafe5ffc750d3fe09aa4c6a9c472)
Params를 RequestData로 바꾸고, Response를 ResponseData로 바꿨습니다!!
tanstack query의 onError 기능을 활용하기 위해 try catch (error) 문을 없앴습니다!

refactor: auth 관련 타입 상수명 개선 및 tanstack react query 사용으로 인한 auth api 내부 try catch (error) 제거

---

apps/shelter/src/apis/auth.ts
apps/shelter/src/pages/signup/index.tsx
apps/volunteer/src/apis/auth.ts
apps/volunteer/src/pages/signup/index.tsx
packages/shared/types/apis/auth.ts

- close #101 
* [refactor(shared): 이메일 인증 관련 타입명 변경](https://github.com/Anifriends/Anifriends-Frontend/commit/b5fa355086c6a9f60f9f47f1013b10309184fc4f)
* [refactor(shelter, volunteer): 이메일 인증 관련 변경된 타입명으로 수정](https://github.com/Anifriends/Anifriends-Frontend/commit/c6d2045fa7642f89b6d56739ee9528ed06780258)
* [feat(shelter, volunteer): SignupPage 컴포넌트 msw 관련 로직 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/74e83dcc46fef2503f450082842190fa851124b6)
* [feat(volunteer): SignupPage의 로그인 버튼에 로그인 화면으로 이동하는 로직 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/5d8a559fc186176dc85288734c34743738f5b8c5)

feat: 보호소앱과 봉사자앱의 회원가입 페이지의 msw 연동 및 관련 로직 추가

---

apps/shelter/src/pages/signin/index.tsx
apps/shelter/src/pages/signup/index.tsx
apps/shelter/src/react-query.d.ts
apps/volunteer/src/pages/signin/index.tsx
apps/volunteer/src/pages/signup/index.tsx
apps/volunteer/src/react-query.d.ts

- close #127 
* [feat(shelter, volunteer): AxiosError 내용이 담긴 react-query.d.ts 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/248d16cfa70537510050bb17b7381395e90b71c2)
* [refactor(shelter, volunteer): Signin, Signup의 useMutation의 generics 제거](https://github.com/Anifriends/Anifriends-Frontend/commit/665a2dbd1f9c25ae22df18555239e48ddd8adff1)

refactor: @tanstack/react-query의 기본 Error 타입 AxiosError로 변경

---

packages/shared/components/Tabs.tsx

- close #170 
* [feat(shared): Tabs 공통 컴포넌트 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/2387b1d9855f94f3951750217a2e720e3f9e30a6)
```tsx
import Tabs from 'shared/components/Tabs';
export default function VolunteersProfilePage() {
return (
<Tabs
tabs={[
['봉사 후기', <p key={1}>봉사 후기</p>],
['봉사 이력', <p key={2}>봉사 이력</p>],
['봉사 소감', <p key={3}>봉사 소감</p>],
]}
/>
);
}
```

feat(shared): Tabs 공통 컴포넌트 추가

---

packages/shared/apis/axiosInterceptor.ts
packages/shared/components/LocalErrorBoundary.tsx
packages/shared/package.json
pnpm-lock.yaml

- close #187
- LocalErrorBoundary 컴포넌트를 만들었습니다.
- 유효한 토큰이 있을때만 헤더에 유효한 정보를 넣도록 구현했습니다.
- 예시 사용법
```tsx
import 'shared/components/LocalErrorBoundary'
export default function VolunteersPage() {
return (
<LocalErrorBoundary>
<Suspense fallback={<p>글목록 로딩중...</p>}>
<Recruitments />
</Suspense>
</LocalErrorBoundary>
);
}
```
- 토큰이 만료됐을때의 예외를 처리하는 Global ErrorBoundary도 만들려고 했는데 아직 인증과 관련된 api들이 완전하지 않은 것 같아 나중에 구현해야 할 것 같습니다.

feat: Local ErrorBoundary 및 Global ErrorBoundary 추가

---

apps/shelter/src/pages/settings/password/index.tsx
apps/shelter/src/pages/signin/index.tsx
apps/shelter/src/pages/signup/index.tsx
apps/volunteer/src/pages/settings/password/index.tsx
apps/volunteer/src/pages/signin/index.tsx
apps/volunteer/src/pages/signup/index.tsx
packages/shared/utils/validations.ts

- close #207 
* [refactor(shelter, volunteer): signin 페이지의 zod를 공통화된 validations으로 변경](https://github.com/Anifriends/Anifriends-Frontend/commit/0a24bc771d5ab9ad66234e6676eb59465535e007)
* [refactor(shelter, volunteer): signup 페이지의 zod를 공통화된 validations으로 변경](https://github.com/Anifriends/Anifriends-Frontend/commit/2d05370f38f759fb6b5bdb35f446604ffb5df6fc)
* [refactor(shelter, volunteer): SettingsPassword 페이지의 zod를 공통화된 validations으로 변경](https://github.com/Anifriends/Anifriends-Frontend/commit/a0475f49ec94f8185bfe221fe427593ca9b2cfff) 
* [fix(shared): validations의 oldPassword 항목 오타 수정](https://github.com/Anifriends/Anifriends-Frontend/commit/0b4ee6e9d1d5091edd19279645ec8b8b695d2c4b)

refactor: 공통화로 묶은 zod validation로 기존 페이지들(Signin, Sigup, SettingsPassword) 변경

---

apps/shelter/src/pages/volunteers/detail/_hooks/useGetVolunteerDetail.ts
apps/shelter/src/pages/volunteers/detail/index.tsx
apps/shelter/src/pages/volunteers/update/index.tsx
packages/shared/apis/common/Recruitments.ts

- close #219
봉사상세조회 response 데이터의 키값을 다음과 같이 변경하여 query data 에 저장했습니다.
```
recruitmentTitle: title,
recruitmentContent: content,
recruitmentApplicantCount: applicant,
recruitmentCapacity: capacity,
recruitmentStartTime: startTime,
recruitmentEndTime: endTime,
recruitmentDeadline: deadline,
recruitmentCreatedAt: createdAt,
recruitmentUpdatedAt: updatedAt,
recruitmentImageUrls: imageUrls,
recruitmentIsClosed: isClosed,
```

feat: 봉사모집 상세조회 useQuery  hook  리팩토링

---

apps/volunteer/src/apis/review.ts
apps/volunteer/src/mocks/handlers/review.ts
apps/volunteer/src/pages/shelters/reviews/update/index.tsx
apps/volunteer/src/types/apis/review.ts
packages/shared/hooks/useUploadPhoto.ts

- close #223 
- useUploadPhoto hook 에 기존 이미지 url 들을 상태로 바꿔주는 `setImageUrls()` 함수 추가
- 봉사 리뷰 상세 조회하는 mock API 추가
- 봉사 후기 페이지 진입 시, 기존 후기 데이터를 form 에 뿌려주는 기능 추가

feat(volunteer): 봉사 후기 수정 페이지 진입 시, 기존 데이터 form 에 넣어주는 기능 추가 및 msw 연결

---

apps/shelter/src/mocks/handlers/recruitment.ts
apps/shelter/src/pages/volunteers/_hooks/useVolunteerRecruitItem.ts

- close #226
봉사자 모집글 리스트에서 아이템 변경시, 캐싱된 서버 상테 업데이트하는 기능을 추가했습니다.
- 봉사자 모집글 리스트에서 각기 다른 데이터를 가진 아이템을 보여주기 위해 `getRandomDummyRecruitment()` 함수를 임의로 만들었습니다

feat(shelter): 봉사자 모집글 리스트에서 아이템 변경시, 캐싱된 서버 상테 업데이트하는 기능 추가

---

apps/shelter/src/mocks/browser.ts
apps/shelter/src/mocks/handlers/image.ts
apps/shelter/src/pages/volunteers/detail/_hooks/useGetVolunteerDetail.ts
apps/shelter/src/pages/volunteers/update/index.tsx

- close #230 
봉사자 모집글 수정 페이지 진입 시, 기존 이미지 리스트 보여주는 기능을 추가했습니다.
- useUploadPhoto hook 의 setImageUrls 를 사용하여 구현

feat(shelter): 봉사자 모집글 수정 페이지 진입 시, 기존 이미지 리스트 보여주는 기능 추가

---

packages/shared/components/LocalErrorBoundary.tsx

- close #255 
* [fix(shared): LocalErrorBoundary에서 로그인 이동 'login'에서 'signin'으로 변경](https://github.com/Anifriends/Anifriends-Frontend/commit/0f5a06f4abbdc42a98f589d0c2613b16809246b4)

fix(shared): LocalErrorBoundary에서 로그인 이동 'login'에서 'signin'으로 변경

---

packages/shared/components/AlertModal.tsx
packages/shared/layout/BottomNavBar/index.tsx
packages/shared/layout/Header/DefaultHeader/index.tsx

- close #260 
- 바텀 네비게이션 바의 마이페이지 이동 버튼 클릭
- 헤더의 알림 페이지 이동 버튼 클릭
- 헤더의 설정 페이지 이동 버튼 클릭

feat(shared): 바텀 네비게이션 바와 헤더에 유저 인증 필요한 경우 모달창 띄우는 기능 추가

---

packages/shared/components/EditPhotoItem.tsx
packages/shared/hooks/useUploadPhoto.ts
packages/shared/package.json
packages/shared/utils/image.ts
pnpm-lock.yaml

- close #251 
- 이미지를 특정 MB size 이하로 리사이징하는 util 함수를 추가했습니다.
- useUploadPhoto hook 에서 이미지 업로드 API 호출 전, 이미지를 2MB 이하의 크기로 리사이징하는 로직을 추가했습니다.

feat(shared): 이미지 resize util 함수 추가 및 useUploadPhoto hook 에 이미지 리사이징 기능 추가

---

apps/shelter/src/pages/signin/index.tsx
apps/volunteer/src/pages/signin/index.tsx

- close #265 
* [feat(shelter, volunteer): 원인 미상의 에러 발생시의 toast description 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/54caee592607c6acb9f964430c2a3f3fed55acd1)
* [feat(shelter, volunteer): 동일한 목적의 toast 중복 호출 제거](https://github.com/Anifriends/Anifriends-Frontend/commit/3984cd15e825d026e6cf56fa8d42b9033c618a79)
https://github.com/Anifriends/Anifriends-Frontend/assets/66409882/03b8510f-e346-463a-a95e-8486fec6c862
동일한 목적의 toast는 한 번만 호출하도록 하고 description이 바뀌도록 하였습니다!! 🙋🏻‍♂️

feat: 로그인 에러 상황시 toast error message 빈 값 처리, toast 중복 호출 제거

---

packages/shared/components/LocalErrorBoundary.tsx

- close #278 
* [fix(shared): LocalErrorBoundary에서 버튼 클릭 시 error boundary 초기화 과정 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/72e0b80be39ae497f5519320242d4c6e7d8d08e7)
https://github.com/Anifriends/Anifriends-Frontend/assets/66409882/105f00bf-ec8c-4017-ae39-5a78711f4fdb
resetErrorBoundary를 버튼 클릭 시 모든 과정에 추가하여 error boundary를 초기화하였습니다!! 🙋🏻‍♂️

fix(shared): LocalErrorBoundary에서 버튼 클릭 시 error boundary 초기화 과정 추가

---

apps/shelter/src/pages/my/index.tsx
apps/volunteer/src/pages/settings/index.tsx

- close #296
- 보호소, 봉사자 앱에 로그인 기능을 추가했습니다.
- 앱의 상태와 로컬 스토리지를 삭제하는 방식으로 구현했습니다

feat: 로그아웃 기능 추가

---

apps/shelter/src/pages/volunteers/detail/index.tsx
apps/volunteer/src/pages/volunteers/detail/index.tsx

- close #205 
이미지 url 이 빈 배열인 경우, 이미지 캐러샐을 랜더링 하지 않도록 수정했습니다.

fix(common): 봉사자 및 보호소 앱의 상세 페이지에서 이미지가 없으면 캐러샐 랜더하지 않도록 수정

---

apps/shelter/src/pages/my/index.tsx

- close #305 
- 마이페이지의 로그아웃 버튼 중복을 제거했습니다.
- 마이페이지의 하단 padding 을 50px 추가했습니다.

fix(shelter): 마이페이지의 로그아웃 버튼 중복 제거 및 padding bottom 추가

---

apps/shelter/src/pages/settings/account/index.tsx
apps/shelter/src/pages/volunteers/detail/index.tsx
apps/volunteer/src/apis/volunteer.ts
apps/volunteer/src/pages/my/_components/MyReviews.tsx
apps/volunteer/src/pages/my/index.tsx
apps/volunteer/src/pages/settings/account/index.tsx
apps/volunteer/src/pages/volunteers/detail/_hooks/useFetchRecruitmentDetail.ts

- close #313
-[x] 봉사자앱의 마이페이지에서 "OOO"님의 봉사횟수... 의 이름이 dummy 데이터로 있는것을 바꿨습니다.
-[x] 보호소앱의 모집삭제를 하면 toast 로 알림을 추가했습니다. (모달로 재확인을 하지않음)
-[x] 수정 정보 실패시 toast 로 수정이 실패했습니다를 알려줍니다.
-[x] 봉사자앱 계정정보수정에서 이미지 수정시에 imageUrl: {} 로 전송되는것을 수정했습니다.

feat: toast 알림 추가, bug 봉사자앱 계정정보수정 imageUrl { } 로 요청 수정

---

apps/shelter/src/mocks/handlers/recruitment.ts
apps/shelter/src/pages/manage/apply/_components/ManageApplyItem.tsx

- close #328 
* [feat(shelter): 봉사 신청 상태 수정 msw에 403, 404 추가](https://github.com/anifriends/frontend/commit/737bec7fe6c05d328cfdfb68ac4c5c7a2604fd95)
* [refactor(shelter): updateToast로, toast 설명의 fontWeight 변경, useMutation에 onError 추가](https://github.com/anifriends/frontend/commit/7e3be70631c258f99fdd0115956fe7848248647e) 
https://github.com/anifriends/frontend/assets/66409882/d26ec3e8-2923-420b-bca7-96b514705dd8
신청 상태가 수정되면 toast가 생성되어 밀려 ux적으로 불편할 수 있는 상황을 고려하여 toast id를 지정하여 toast는 하나만 생성이 되게끔 구현하였습니다.

feat: 봉사자 신청현황 페이지 toast updatToast로 변경, onError 추가, toast 설명 폰트 속성 변경

---

packages/shared/package.json
packages/shared/tsconfig.json
packages/tsconfig/base.json
packages/tsconfig/vite.json

- close #340 
* [chore(tsconfig): base.json에서 moduleResolution Bundler로 변경](https://github.com/anifriends/frontend/commit/51f79378550f380466e2e77d921b0a2bede80588)
* [chore(shared): package.json에 type module 추가](https://github.com/anifriends/frontend/commit/a0c70400b9692c79abc023e753c330158869b5c2)
* [chore(shared, tsconfig): tsconfig 및 관련 파일 오름차순 정렬, 중복 제거, target ES2020으로 변경](https://github.com/anifriends/frontend/commit/8e27db7b468bfd9718ee77998020cad124779a95)
* 권장되지 않은 moduleResolution의 Node에서 Bundler로 변경하였습니다!
* 최신 브라우저와 호환성을 위해 target을 ES2020으로 변경하였습니다!

chore: tsconfig 및 관련 파일 수정, package.json에 type module 추가
