.github/workflows/build-test.yml
- close #8 
ci할때 깃허브 액션을 이용한 빌드테스트를 추가했습니다
x
x
=> chore: 빌드 테스트 깃허브 액션 추가

apps/shelter/package.json, apps/shelter/vite.config.ts, apps/volunteer/package.json, apps/volunteer/vite.config.ts, packages/eslint-config-custom/package.json, packages/tsconfig/package.json, packages/ui/package.json, pnpm-lock.yaml
=> chore: 봉사자, 보호소 프로젝트에서 vite-plugin 변경

.lintstagedrc, apps/shelter/package.json, apps/shelter/tsconfig.json, apps/shelter/vite.config.ts, apps/volunteer/package.json, apps/volunteer/tsconfig.json, apps/volunteer/vite.config.ts, pnpm-lock.yaml
=> chore : vite 절대경로 설정

apps/shelter/vercel.json, apps/volunteer/vercel.json
- close #33
vercel.json을 추가해 라우팅 문제를 해결했습니다.
=> fix : vercel 배포 링크에서 라우팅 오류 해결 

packages/shared/api/axiosInstance.ts, packages/shared/api/axiosInterceptor.ts, packages/shared/constants/baseURL.ts, packages/shared/package.json, pnpm-lock.yaml
=> feat: axios Interceptor 추가

packages/shared/components/InfoTextList.tsx
- close #41 
* [fix(shared): 단위를 %에서 rem, calc를 활용하여 변경](https://github.com/Anifriends/Anifriends-Frontend/commit/bf906f1083878da82cb9f65c78862bbd5e218ab4)
https://github.com/Anifriends/Anifriends-Frontend/assets/66409882/2e9d8973-114d-493c-b54e-841d5d0b49c8
=> fix(shared): 단위를 %에서 rem, calc를 활용하여 변경

packages/shared/components/ImageCarousel.tsx
- close #53 
* [feat(shared): ImageCarousel 컴포넌트 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/dc879f549998f9706302ff76a33268a894c6ce98)
https://github.com/Anifriends/Anifriends-Frontend/assets/66409882/eeab5eea-5f6e-485b-9ef9-9b648bbd964d
https://github.com/Anifriends/Anifriends-Frontend/assets/66409882/5e50afa8-0200-4db3-818e-05b35d8134be
구조적으로는 동작하나 ts에러에 걸려서 어쩔 수 없이 "그 친구"를 적어버렸습니다... ㅠㅠ 😂
양해 부탁드립니다! 🙏🙋🏻‍♂️
```tsx
export default function VolunteersPage() {
const imageUrls = [
'https://images.unsplash.com/photo-1682687221248-3116ba6ab483?auto=format&fit=crop&q=80&w=2574&ixlib=rb-4.0.3&ixid=M3wxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
'https://images.unsplash.com/photo-1694188119956-e28ffd3cf785?auto=format&fit=crop&q=60&w=800&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxl …
```
=> feat(shared): ImageCarousel 컴포넌트 추가

packages/shared/components/ReviewItem.tsx
- close #20
children은 카드 가장 위에 들어갈 항목입니다. 보호소나 봉사자의 프로필 ui를 매개변수로 넣습니다.
content는 리뷰 게시글에 해당하는 콘텐츠입니다.
images는 카드 하단에 들어가는 이미지 url리스트입니다.
showMenuButton은 버튼을 보여주는 여부를 나타내는 boolean입니다
onUpdate, onDelete는 메뉴의 아이템 중 수정, 삭제가 일어났을 때 실행시킬 함수입니다.
```typescript
type ReviewItemProps = {
children: React.ReactNode;
content: string;
images: string[];
showMenuButton?: boolean;
onUpdate?: VoidFunction;
onDelete?: VoidFunction;
};
```
- 이미지 border만 제외하고 봐주세요.
onUpdate, onDelete모두 VoidFunction은 아닐 것 같습니다. 그런데 구현에 따라 함수의 형태가 달라지기 때문에 지금 함수의 타입을 정하기 힘들다고 생각해 일단은 VoidFunction으로 해놓았습니다.
=> feat : ReviewItem 컴포넌트

apps/shelter/src/pages/my/index.tsx, packages/shared/components/ProfileInfo.tsx, packages/shared/components/SettingGroup.tsx, packages/shared/components/SettingItem.tsx
- close #56 
보호소 앱 마이페이지를 개발했습니다.
- 내부 컨텐츠가 늘어나니까 공통레이아웃 스타일이 깨지는 버그를 발견했습니다.
- 레이아웃이 깨지지 않도록 수정해서 다음 PR 에 올리도록 하겠습니다!
ex) 끝까지 스크롤한 경우
=> feat: 보호소 앱 마이페이지 UI 개발

apps/shelter/src/constants/path.ts, apps/shelter/src/pages/my/reviews/VolunteerProfile.tsx, apps/shelter/src/pages/my/reviews/index.tsx, packages/shared/assets/icon_review_next.svg, packages/shared/components/InfoItem.tsx, packages/shared/components/InfoList.tsx, packages/shared/components/InfoSubtext.tsx, packages/shared/components/InfoTextItem.tsx, packages/shared/components/InfoTextList.tsx, packages/shared/components/Label.tsx, packages/shared/components/ReviewItem.tsx
- close #61 
- 봉사 리뷰 페이지 ui를 만들었습니다.
- 헤더와 제목 사이 간격, 제목과 리뷰 아이템의 간격이 좁지 않나 하는 생각이 듭니다.
- 간격을 추후 늘릴까 고민중입니다.
=> feat: 봉사 리뷰 페이지 ui

apps/shelter/src/pages/volunteers/RecruitDateText.tsx, apps/shelter/src/pages/volunteers/RecruitItem.tsx, apps/shelter/src/pages/volunteers/index.tsx, apps/volunteer/src/pages/volunteers/VolunteerRecruitItem.tsx
- close #65
봉사 모집글 리스트 페이지 ui를 개발했습니다
- 날짜를 파싱하는 로직은 아직 작성하지 않았습니다.
- 게시글 수정, 삭제하는 함수도 아직은 넣지 않는게 좋다고 생각해서 추후 추가할 예정입니다.
- Tanstack query의 infiniteQuery를 활용한 무한 스크롤 구현에 대해서 공부해야 할 것 같습니다.
- 처음에 실수로 봉사자 어플의 봉사자 리스트 페이지를 만들었습니다. 봉사자 어플에 관련 컴포넌트를 이동시켰습니다
=> feat: 봉사 모집글 리스트 페이지 ui

apps/shelter/src/mocks/handlers/auth.ts, apps/volunteer/src/mocks/handlers/auth.ts, packages/shared/apis/shelters/Shelter.ts, packages/shared/components/CustomButton.tsx, packages/shared/components/Header.tsx
- close #이슈번호
- 저번 api 함수 머지할때 컨플릭트를 해결하고 develop에 머지했는데 머지 컨플릭트 해결하는 커밋하는 과정에서 오류가 섞인 것 같습니다. 이를 해결했습니다.
- eslint 옵션을 수정하면서 no-console 룰을 위반하는 파일들이 몇개 발생했습니다. 제가 작업한 부분의 console은 제거했습니다
- 초기세팅때 임시로 만들었던 컴포넌트들을 제거했습니다.
=> hotfix: api 함수 에러 해결

apps/shelter/src/pages/signin/index.tsx, apps/volunteer/src/pages/signin/index.tsx
- close #81 
* [feat(volunteer): SigninPage 컴포넌트에 로직 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/acd7ade077495ad9f8628e90d7e9f7cec0a600c0)
* [feat(shelter): SigninPage 컴포넌트에 로직 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/bf3c61c613ba6d7dc14e135d2fc2942ca7873fc2)
=> feat: 보호소앱과 봉사자앱의 로그인 페이지의 로직 추가

apps/shelter/src/pages/signup/index.tsx, apps/volunteer/src/constants/gender.ts, apps/volunteer/src/pages/signup/index.tsx, apps/volunteer/src/types/gender.ts
- close #84 
* [feat(shelter): SignupPage 컴포넌트에 로직 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/0fcb854733c176fb707563c425e9d31764016f3f)
* [feat(volunteer): 사람 관련 성별이 담긴 gender를 constants에 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/97481bb4096d3337bf7c87e286624faaaa9da5a9)
* [feat(volunteer): 사람 관련 성별이 담긴 gender 타입들을 types에 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/4428ecbeaf665d8df3285acc62d0ae8a4268c1e6)
* [feat(volunteer): SignupPage 컴포넌트에 로직 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/49dfe198d1652b634336ffd96cd1a1150f8cd0b7)
회원가입 API 관련 로직은 MSW를 하면서 작성하겠습니다!
또한 이후 로직을 컴포넌트로 분리하겠습니다!
=> feat: 보호소앱과 봉사자앱의 회원가입 페이지의 로직 추가

apps/shelter/src/pages/volunteers/hooks/useIntersection.tsx
- close #88 
- Intersection observer을 이용한 무한 스크롤 훅을 추가했습니다.
=> feat(shelter): 무한 스크롤 훅 추가

apps/shelter/src/pages/volunteers/detail/AlertModal.tsx, apps/shelter/src/pages/volunteers/detail/index.tsx, packages/shared/components/InfoTextList.tsx
- close #93 
infoList 컴포넌트를 사용하다가 경로가 잘못된 점을 발견하여 수정하였습니다.
봉사자 모집 상세 페이지 ui 를 구현하였습니다. 
https://github.com/Anifriends/Anifriends-Frontend/assets/117665863/7f9f41d4-7280-409f-b2de-b6da93134016
Label 컴포넌트를 사용할때 색상 타입 중에 gray 색상이 없어서 수정이 필요할것 같습니다.
Label 옆에 텍스트가 있으면 LabelText 컴포넌트를 사용하는데 이때 label 색상을 수정이 불가능한것 같습니다.
LabelText 컴포넌트에서도 Label 색상을 정할수 있도록 하면 좋지 않을까요..?
=> feat: 보호소 봉사모집 상세페에지 UI 및 버튼 로직 구현

apps/shelter/src/apis/auth.ts, apps/shelter/src/mocks/handlers/auth.ts, apps/shelter/src/types/apis/auth.ts, apps/volunteer/src/apis/auth.ts, apps/volunteer/src/mocks/handlers/auth.ts, apps/volunteer/src/types/apis/auth.ts, packages/shared/types/apis/auth.ts, packages/shared/types/apis/error.ts
- close #113 
* [feat(volunteer): auth(signin, signup) mock handler 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/4d01a8edc616f643aa47a79efd1cc1ace69f418e)
* [feat(shelter): auth(signin, signup) mock handler 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/f23fc724f0354b67e60bbc16ce6425c81b880c2d)
* [feat(shared): error 관련 response data type 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/a6cbd2d4d4d410851bacf6767ad8bb1514910bd5)
* [feat(shared): auth(signin, signup) 관련 type 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/942381d93f58aba5e4ff9f16bc5196ac82ff1357)
* [feat(shelter): auth(signin, signup) 관련 type 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/006f640db5895dd0dcff69af1e63c62d15c29288)
* [feat(volunteer): …
=> feat: 보호소앱, 봉사자앱의 auth(signin, signup) api, api 관련 type, msw handler 추가

apps/shelter/src/pages/signin/index.tsx, apps/volunteer/src/pages/signin/index.tsx
- close #102 
* [feat(shelter, volunteer): SigninPage 컴포넌트 msw 관련 로직 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/163182f3a288155e3f1a294c09d49d1e17d2db5b)
=> feat(shelter, volunteer): SigninPage 컴포넌트 msw 관련 로직 추가

apps/shelter/src/mocks/browser.ts, apps/shelter/src/mocks/handlers/recruitmentDetail.ts, apps/shelter/src/pages/volunteers/detail/_hooks/useGetVolunteerDetail.ts, apps/shelter/src/pages/volunteers/detail/index.tsx, packages/shared/components/LabelText.tsx, packages/shared/constants/date.ts, packages/shared/utils/date.ts
- close #109 
봉사모집 상세페이지 msw 연결하였습니다.
https://github.com/Anifriends/Anifriends-Frontend/assets/117665863/c761a46f-89b3-4381-a950-37f8d2473400
봉사상세페이지 useQuery 키를 ['recruitment' {recruitmentId}] 로 관리하는데 어떠신가요..?
=> Feat: 봉사모집 상세페이지 msw 연결

apps/shelter/src/pages/volunteers/_components/PlusIcon.tsx, apps/shelter/src/pages/volunteers/index.tsx, packages/shared/apis/axiosInstance.ts
- close #125 
- axiosInstance에 withcredentials: true 속성을 추가했습니다.
- 봉사자 모집 리스트 페이지에 플로팅을 추가했습니다.
- 플로팅 버튼을 클릭시 게시글 작성 페이지로 이동합니다
=> feat: 봉사자 리스트 페이지에 플로팅 버튼 추가

apps/shelter/src/pages/manage/attendance/index.tsx
- close #128 
- 출석 관리 페이지 ui를 만들었습니다
- Table 태그를 이용해서 만들었는데 box와 같은 div류 태그들로 변경할지 고민중입니다. 바꾼다고 해도 나중에 바꿀것 같긴합니다
=> feat : 봉사자 출석 관리 페이지 ui

apps/shelter/src/pages/settings/password/index.tsx, apps/volunteer/src/pages/settings/password/index.tsx, packages/shared/components/LogoImageBox.tsx, packages/shared/png.d.ts
- close #137 
* [feat(shared): 이미지를 위한 png.d.ts 파일 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/fce96869f12bc97196ff10566f7c81f999f82c6a)
* [feat(shared): LogoImageBox 컴포넌트 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/c603b3db92355911c8339c49d2708f17dcdf53b5)
* [feat(shelter, volunteer): 비밀번호 변경 페이지 UI 및 로직 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/95a47f0f2926e15178e467272ac3f246bf1e44a6)
* #139 완료되면 바로 진행하겠습니다!!
=> feat: 보호소앱, 봉사자앱 비밀번호 변경 페이지 UI 및 로직 추가

apps/shelter/src/pages/volunteers/write/index.tsx
- close #129
- 봉사자 모집글 작성 페이지의 ui를 만들었습니다
- 글 작성 페이지와 수정 페이지의 ui가 같기 때문에 우선 글 작성 페이지의 ui만 만들었습니다. 글 수정 페이지의 ui는 로직을 추가하며 같이 추가하려고 합니다
=> feat(shelter): 봉사자 모집글 추가 페이지 ui 추가

apps/shelter/src/pages/volunteers/detail/index.tsx, apps/volunteer/src/constants/path.ts, apps/volunteer/src/pages/volunteers/detail/index.tsx, packages/shared/components/AlertModal.tsx
- close #133 
https://github.com/Anifriends/Anifriends-Frontend/assets/117665863/8911aa36-f317-490e-9be5-c272a1f342c7
확인을 알려주는 Modal 창을 공통컴포넌트로 이동했는데 공통컴포넌트로 보아도 되는걸까요?
봉사자앱, 보호소앱의 상세페이지에서만 사용을 하고있는데 공통컴포넌트로 빼는게 좋을지 궁금합니다.
하단 버튼의 상위요소에 backgrounColor 에 대한 논의가 있는것 같아서 결정이 되면 수정하는 방안으로 진행하겠습니다. 
현재는 버튼의 상위요소에 backgroundColor를 넣지 않았습니다.
=> feat: 봉사자앱 봉사 모집 상세 페이지 UI 개발

apps/shelter/src/assets/CkCheck.tsx, apps/shelter/src/constants/recruitment.ts, apps/shelter/src/pages/manage/apply/_components/ApplyInfoItem.tsx, apps/shelter/src/pages/manage/apply/_components/ApprovedCountBox.tsx, apps/shelter/src/pages/manage/apply/_components/ManageApplyItem.tsx, apps/shelter/src/pages/manage/apply/index.tsx, apps/shelter/src/types/apis/recruitment.ts, apps/shelter/src/types/recruitment.ts, apps/volunteer/src/pages/signup/index.tsx, apps/volunteer/src/types/apis/auth.ts, apps/volunteer/src/types/gender.ts, packages/shared/constants/gender.ts, packages/shared/types/gender.ts, packages/shared/utils/date.ts
- close #141 
* [rename(volunteer): gender 관련 types, constants를 shared로 이동 및 연관 경로 수정](https://github.com/Anifriends/Anifriends-Frontend/commit/13de27308000a9dad7cd8ae437ddd055f16b9cbf)
* [feat(shelter): recruitment의 applicant 상태 관련 상수 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/9babf073ff806be99a275cbede23e97123788ce5)
* [feat(shelter): recruitment의 applicant 상태 관련 타입 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/e61a35323555818b5ef7b46332ec97405367329c)
* [fix(shelter): recruitment의 applicant 상태, 성별 관련 타입 교체](https://github.com/Anifriends/Anifriends-Frontend/commit/16b0ad4d83c93cc4d666691dfd0cc7c40f14300e)
* [feat(shelter): CkCkeck svg 아이콘 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/86ae63a0d943cabe7631a28b32310df78f7e3bc8)
* …
=> feat: 보호소앱 봉사 신청 현황 페이지 UI 추가 및 gender, applicant 관련 type 공통화, 정리

apps/volunteer/src/pages/shelters/profile/_components/ShelterRecruitments.tsx, apps/volunteer/src/pages/shelters/profile/_components/ShelterReviews.tsx, apps/volunteer/src/pages/shelters/profile/index.tsx
- close #173
봉사자앱의 보호소 프로필 페이지 UI 를 만들었습니다.
https://github.com/Anifriends/Anifriends-Frontend/assets/117665863/3ab85b76-0deb-4cef-86b2-f3d6cdc55077
=> feat: 봉사자앱 보호소프로필 페이지 UI 개발

packages/shared/components/Tabs.tsx
- close #181 
* [feat(shared): Tabs 컴포넌트 내부 배경 색상 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/6d1eb1771767d81b230ac8d3cc254192cc5180fb)
=> feat(shared): Tabs 컴포넌트 내부 배경 색상 추가

packages/shared/fonts/index.tsx
- close #178 
* [fix(shared): font의 고정된 fontWeight 제거](https://github.com/Anifriends/Anifriends-Frontend/commit/c96f7ebaaeb66742a86ecc6f466c388744c67f6d)
=> fix(shared): font의 고정된 fontWeight 제거

apps/volunteer/src/pages/settings/index.tsx, apps/volunteer/src/routes/index.tsx
- close #175
- 봉사자 세팅 페이지를 구현했습니다.
로그아웃은 추후에 추가하겠습니다.
=> feat(volunteer): 봉사자 어플 세팅 페이지 추가

packages/shared/package.json, packages/shared/utils/validations.ts, pnpm-lock.yaml
- close #169 
* [chore(shared): zod 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/1387e017ac5748a3c188b55cfff606619e3b0e86)
* [feat(shared): form 유효성 검증을 위한 validations 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/13a3fa2d3c89d2838ca0fa1e932208e1651867ae)
=> feat: zod 유효성 검사 항목들 공통화 

apps/volunteer/src/constants/path.ts, apps/volunteer/src/pages/shelters/reviews/update/index.tsx, apps/volunteer/src/pages/shelters/reviews/write/index.tsx
- close #194
봉사 후기 작성 및 수정 시, url 로 부터 shelterId 및 reviewId 를 가져와야해서, 라우팅을 수정했습니다.
=> feat(volunteer): 봉사 후기 작성 및 수정 페이지 라우팅 수정

packages/shared/fonts/index.tsx, packages/shared/theme/index.ts
- close #198 
* [feat(shared): font의 font-weight 제거 후 하나로 통일](https://github.com/Anifriends/Anifriends-Frontend/commit/d3c3dfa227c7a10e525fc852261a4787349929d6)
* [feat(shared): heading, body font를 IBMPlexSans로 통일](https://github.com/Anifriends/Anifriends-Frontend/commit/f721c83e2adfcce32e914666f7e466eaf476486c)
=> feat(shared): heading, body font를 font-weight 제거, theme의 font IBMPlexSans로 통일 후 적용

apps/shelter/src/constants/path.ts, apps/shelter/src/pages/volunteers/profile/_components/VolunteerRecords.tsx, apps/shelter/src/pages/volunteers/profile/_components/VolunteerReviews.tsx, apps/shelter/src/pages/volunteers/profile/index.tsx, packages/shared/components/Tabs.tsx
- close #203 
* [fix(shelter): VOLUNTEERS.PROFILE path에 id 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/24567cd61ee9a05b47256c2e108f5b1d2202119d)
* [feat(shared): Tabs 컴포넌트에 sticky 옵션 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/17719a872de67fc1ccb2872d2754a09ff2023cfc)
* [feat(shelter): 더미 데이터와 함께 VolunteerRecords 컴포넌트 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/b323069cd514a8e8705af20a16403288363f30f7)
* [feat(shelter): 더미 데이터와 함께 VolunteerReviews 컴포넌트 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/d8a86ce1c135ccfc9cb638d656377eee11eae34b)
* [feat(shelter): 더미 데이터와 함께 VolunteersProfilePage 컴포넌트 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/e9ac1b5aa15f0efc5e0774239ac935fad7c6449f)
=> feat: 보호소의 봉사자 프로필 페이지 UI 추가

apps/volunteer/src/pages/shelters/reviews/_components/ReviewSubmitButton.tsx, apps/volunteer/src/pages/shelters/reviews/_constants/reviews.ts, apps/volunteer/src/pages/shelters/reviews/_schema/reviewSchema.ts, apps/volunteer/src/pages/shelters/reviews/update/index.tsx, apps/volunteer/src/pages/shelters/reviews/write/index.tsx
- close #153 
봉사 후기 작성 및 수정 페이지의 UI 와 form validation 로직을 개발했습니다
=> feat(volunteer): 봉사 후기 작성 및 수정 페이지 UI 개발

apps/volunteer/src/apis/review.ts, apps/volunteer/src/apis/shelter.ts, apps/volunteer/src/mocks/handlers/shelter.ts, apps/volunteer/src/pages/shelters/profile/_components/ShelterRecruitments.tsx, apps/volunteer/src/pages/shelters/profile/_components/ShelterReviews.tsx, apps/volunteer/src/pages/shelters/profile/index.tsx
- close #185
봉사자앱의 보호소프로필 페이지 msw 를 연결하였습니다.
https://github.com/Anifriends/Anifriends-Frontend/assets/117665863/803531cc-17f9-4c96-a8ed-caed63651630
=> feat: 봉사자앱의 보호소프로필 페이지 msw 연결

apps/shelter/src/pages/volunteers/update/index.tsx, apps/shelter/src/pages/volunteers/write/index.tsx
=> feat(shelter): 봉사 모집 게시글 작성 및 수정 페이지 form 제출 시, request 에 이미지 url 추가

packages/shared/components/LocalErrorBoundary.tsx, packages/shared/layout/index.tsx, packages/shared/utils/errorMessage.ts
- close #192
- 에러바운더리에 권한이 없을 때 혹은 다른 문제가 발생했을 때에도 에러를 보여주도록 수정했습니다
- local errorboundary로 layout의 outlet을 감싸뒀습니다.
- 글로벌 에러바운더리와 로컬 에러바운더리로 분리해야 하지만 나중으로 미루겠습니다.
=> feat : 에러바운더리 기능 추가 및 적용

packages/shared/theme/index.ts
- close #234 
케밥 케이스로 되어있던 css 프로퍼티를 카멜 케이스로 수정했습니다.
=> fix(shared): global theme의 overscroll-behavior css 속성을 카멜 케이스로 수정

apps/volunteer/src/apis/volunteer.ts, apps/volunteer/src/constants/applicantStatus.ts, apps/volunteer/src/mocks/handlers/volunteer.ts, apps/volunteer/src/pages/my/_components/ApplyRecruitments.tsx, apps/volunteer/src/pages/my/index.tsx, apps/volunteer/src/types/apis/volunteer.ts
- close #227 
* [feat(volunteer): MyPage에 사용되는 applicant 상태 constant 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/76d2c9f318570d70033fa52c9682fc344faebb55)
* [feat(volunteer): MyPage 관련 type volunteer에 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/83dc3176092a4f38ea0cd2b2a341df2f03cf3a3f)
* [feat(volunteer): 봉사 리스트 조회 api volunteer에 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/5f3f244f1642ca5ea83232944e7e2e8cf8f4c542)
* [feat(volunteer): Mypage의 봉사 리스트 관련 mock handler 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/d3dc919ecd1b50b76f00c1b2d849e9a06d444dca)
* [feat(volunteer): ApplyRecruitments 컴포넌트 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/c0e4efc3554ebe0249ca91406828d12fbb0cdbd3)
* [feat(volunteer): Mypage에 …
=> feat: 봉사자 마이페이지에서 신청한 봉사후기 UI 및 msw 연결

apps/shelter/src/App.tsx, apps/shelter/src/pages/my/_hooks/useMyPage.ts, apps/shelter/src/pages/my/index.tsx
- close #239 
- 보호소 마이페이지 토글 버튼 디자인을 수정했습니다.
- 보호소 앱의 queryClient stale time 을 50초로 설정했습니다.
=> feat(shelter): 보호소 마이페이지 토글 버튼 디자인 수정 및 useMutation 사용하도록 수정

packages/shared/utils/validations.ts
- close #241 
* [feat(shared): validations 전화번호 형식에 '-' 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/5f8e940ad15757519deeaa1f2a3558b08375bd87)
=> feat(shared): validations 전화번호 형식에 '-' 추가

apps/shelter/src/apis/shelter.ts, apps/shelter/src/mocks/handlers/shelter.ts, apps/shelter/src/pages/my/reviews/VolunteerProfile.tsx, apps/shelter/src/pages/my/reviews/index.tsx, packages/shared/components/ReviewItemSkeleton.tsx, packages/shared/components/ReviewItemSkeletonList.tsx
- close #214
- 리뷰 스켈레톤을 만들었습니다.
- 보호소에 달린 리뷰 페이지에서 > 버튼을 클릭할 때 프로필 페이지로 이동하는 기능을 추가했습니다
=> feat : 리뷰 스켈레톤

apps/shelter/src/main.tsx, apps/volunteer/src/components/WithLogin.tsx, apps/volunteer/src/main.tsx, packages/shared/layout/index.tsx
- close #240
- 보호소 앱 회원가입 페이지를 url로 접근 가능하도록 수정했습니다
- 봉사자앱의 early return이 없는 것을 발견해 추가했습니다.
=> feat : withlogin, layout 수정

apps/shelter/src/apis/shelter.ts, apps/shelter/src/pages/my/reviews/hooks/useFetchShelterReviews.tsx, apps/shelter/src/pages/volunteers/_queryOptions/recruitment.ts, apps/shelter/src/types/apis/recruitment.ts, apps/volunteer/src/apis/volunteer.ts, apps/volunteer/src/pages/shelters/profile/_components/ShelterReviews.tsx, apps/volunteer/src/pages/volunteers/_queryOptions/recruitments.ts, apps/volunteer/src/types/apis/recruitment.ts, apps/volunteer/src/types/apis/review.ts, packages/shared/apis/common/Recruitments.ts, packages/shared/apis/common/Review.ts
- close #202 
* fix(shared, shelter, volunteer): pagination type의 pageSize, pageNumber를 size, page로 변경
=> fix(shared, shelter, volunteer): pagination type의 pageSize, pageNumber를 size, page로 변경

apps/shelter/src/pages/signup/index.tsx, apps/volunteer/src/pages/signup/index.tsx
- close #261 
* [feat(shelter, volunteer): 전화번호 형식 helperText 변경](https://github.com/Anifriends/Anifriends-Frontend/commit/0ccf0c1b74771087e8904482a2febc062bb06735)
=> feat(shelter, volunteer): 전화번호 형식 helperText 변경

apps/shelter/src/pages/animals/index.tsx, apps/shelter/src/pages/chattings/index.tsx, apps/volunteer/src/pages/animals/index.tsx, apps/volunteer/src/pages/chattings/index.tsx, packages/shared/components/NotReady.tsx
- close #267 
* [feat(shared): NotReady 컴포넌트 생성](https://github.com/Anifriends/Anifriends-Frontend/commit/b9ffbdcd741b2f031fd8418e4f918b0154f320dc)
* [feat(shelter, volunteer): animals, chattings 페이지에 NotReady 컴포넌트 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/04b399133dff7d6dbb57f64bc44282a995ce9eff)
=> feat: NotReady 컴포넌트 페이지 추가 및 animals, chattings 페이지에 적용

apps/volunteer/src/constants/applicantStatus.ts, apps/volunteer/src/pages/my/_components/ApplyRecruitments.tsx
- close #272 
* [fix(volunteer): 출석완료, 승인완료 교체](https://github.com/Anifriends/Anifriends-Frontend/commit/75c3b2a7f39b2ea3bb65046d251fdb79aa0598f4)
* [fix(volunteer): APPROVED를 ATTENDANCE로 변경](https://github.com/Anifriends/Anifriends-Frontend/commit/63d816d7cbf504a7d9fde8b86d96347ba8d8a938)
=> fix: 봉사자 마이페이지의 label 상태 출석완료, 승인완료 교체

packages/shared/components/Loader.tsx, packages/shared/layout/index.tsx
- close #275
로딩 상태를 만들어서 로딩 상태일때는 Loader 컴포넌트를 보여주도록 했습니다.
액세스 토큰이 만료되었을때의 에러 처리가 필요합니다
=> fix: 새로고침했을때 자동 로그인이 되지 않는 버그 수정

apps/shelter/src/pages/volunteers/_hooks/useVolunteerRecruitItem.ts, apps/shelter/src/pages/volunteers/index.tsx, apps/shelter/src/pages/volunteers/search/index.tsx
=> bug(shelter): 봉사 모집글 검색 결과 리스트 페이지에서 마감 버튼, 또는 삭제 버튼 눌러도 UI 업데이트 되지 않는 로직 수정

apps/shelter/src/pages/my/index.tsx, apps/shelter/src/pages/volunteers/index.tsx, apps/volunteer/src/pages/my/index.tsx, apps/volunteer/src/pages/volunteers/index.tsx
- close #284 
* [feat(shelter, volunteer): 마이 페이지, 봉사 모집글 리스트 페이지에 padding-bottom 50px 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/9d5de4fa82aef50a86aeae8c0561f6e4eff1a92e)
=> feat(shelter, volunteer): 마이 페이지, 봉사 모집글 리스트 페이지에 padding-bottom 50px 추가

apps/shelter/src/pages/notifications/index.tsx, apps/volunteer/src/pages/notifications/index.tsx
- close #280 
* [feat(shelter, volunteer): 알림 페이지에 준비중 컴포넌트 추가](https://github.com/Anifriends/Anifriends-Frontend/commit/6a5138dcebe585d7b4b69b9f28626e36fc12ec75)
=> feat(shelter, volunteer): 알림 페이지에 준비중(NotReady) 컴포넌트 추가

apps/volunteer/src/pages/my/_components/MyReviews.tsx
- close #291 
* [fix(volunteer): 마이 페이지 MyReview 탭의 initialPageParam을 0으로 수정](https://github.com/Anifriends/Anifriends-Frontend/commit/3f1c5fcde8347749660233449cbb1946f753e567)
=> fix(volunteer): 마이 페이지 MyReview 탭의 initialPageParam을 0으로 수정

apps/shelter/src/pages/volunteers/update/index.tsx, apps/shelter/src/pages/volunteers/write/index.tsx, packages/shared/utils/date.ts
- close #294
- 시간을 입력하고 isoString으로 변환할 시 영국 기준으로 시간이 입력됐기 때문에 시차를 반영한 시간을 입력하도록 수정했습니다
=> fix : 모집글 작성 및 수정 페이지에서 시차가 나는 시간 입력되던 문제 수정

apps/shelter/src/pages/volunteers/detail/_hooks/useGetVolunteerDetail.ts, apps/shelter/src/pages/volunteers/detail/index.tsx
- close #283 
- 기존 useQuery 의 initialData 로 인해 API 조회가 되지 않는 버그가 있었습니다.
- initialData 를 제거하고 useSuspenseQuery 를 사용하도록 수정했습니다.
=> fix(shelter): 봉사자 모집글 상세페이지 API 조회가 되지 않는 버그 수정

apps/volunteer/src/pages/volunteers/detail/_hooks/useFetchRecruitmentDetail.ts, apps/volunteer/src/pages/volunteers/detail/index.tsx, packages/shared/store/authStore.ts
- close #300 
useFetchVolunteersDetail hook 의 인자로 user 정보를 받아오도록 수정했습니다.
=> bug(volunteer): 봉사 상세 페이지에서 비회원인 경우에는 봉사 신청 여부 API 를 요청하지 않도록 수정

apps/shelter/src/pages/volunteers/update/index.tsx
- close #307
모집글 수정 페이지의 처음 페이지 들어갔을때의 시간 오류를 수정하고 suspense를 추가했습니다.
=> fix(shelter): 모집글 수정페이지에서 시간 오류 수정

apps/volunteer/src/pages/shelters/profile/_components/ShelterRecruitments.tsx, apps/volunteer/src/pages/shelters/profile/_components/ShelterReviews.tsx
- close #311 
* [fix(volunteer): 마이 페이지 탭들 내부 useSusepnseInfiniteQuery의 initialPageParam을 0으로 수정](https://github.com/Anifriends/Anifriends-Frontend/commit/efb0b2210c35e9872f85db9a0fcccc76abfe1ff7)
=> fix(volunteer): 마이 페이지 탭들 내부 useSusepnseInfiniteQuery의 initialPageParam을 0으로 수정

apps/volunteer/src/pages/shelters/profile/_components/ShelterRecruitments.tsx, apps/volunteer/src/pages/shelters/profile/_components/ShelterReviews.tsx
=> release: v0.1.9

packages/shared/components/Tabs.tsx
- close #319 
* [feat(shared): Tabs 컴포넌트 내부 route replace 허용](https://github.com/Anifriends/Anifriends-Frontend/commit/d2fcd47a3ac90db67617520b31492e7b794b5e8e)
https://github.com/Anifriends/Anifriends-Frontend/assets/66409882/c7df1110-a5b8-4922-b34a-0cb675e59279
=> feat: Tabs 컴포넌트 route replace true로 설정

apps/shelter/src/pages/settings/account/index.tsx, apps/shelter/src/pages/signup/index.tsx, apps/shelter/src/pages/volunteers/detail/index.tsx, apps/volunteer/src/apis/volunteer.ts, apps/volunteer/src/pages/my/_components/MyReviews.tsx, apps/volunteer/src/pages/my/index.tsx, apps/volunteer/src/pages/settings/account/index.tsx, apps/volunteer/src/pages/signup/index.tsx, apps/volunteer/src/pages/volunteers/detail/_hooks/useFetchRecruitmentDetail.ts, packages/shared/components/ReviewItem.tsx, packages/shared/components/ReviewItemSkeleton.tsx, packages/shared/components/Tabs.tsx
=> release: v0.1.10

packages/shared/utils/toast.ts
- close #324 
* [feat(shared): updateToast util 함수 추가](https://github.com/anifriends/frontend/commit/0e87b6846bf69a06399c274fb0c2a91a01b3d336)
* #315 에서 반복적으로 if...else문을 사용하기 때문에 이를 공통화한 함수 updateToast 함수를 만들었습니다.
=> feat(shared): updateToast util 함수 추가

apps/shelter/src/pages/signup/index.tsx, apps/volunteer/src/pages/signup/index.tsx
- close #323 
* [refactor(shelter, volunteer): signup 페이지 내부 toast updateToast로 변경](https://github.com/anifriends/frontend/commit/0b3193dd02b390e1174bd2da2a0f893a2c74e1ab)
=> refactor(shelter, volunteer): signup 페이지 내부 toast updateToast로 변경

apps/shelter/src/pages/signin/index.tsx, apps/volunteer/src/pages/signin/index.tsx
- close #327 
* [refactor(shelter, volunteer): signin 페이지 내부 toast updateToast로 변경](https://github.com/anifriends/frontend/commit/9ef0e8a524840eab10812920bdb25749575c3e12)
=> refactor(shelter, volunteer): signin 페이지 내부 toast updateToast로 변경

apps/shelter/src/pages/manage/apply/_components/ManageApplyItem.tsx
- close #331 
* [feat(shelter): 봉사자 신청 현황 페이지 신청된 상태가 같을 경우 서버 호출 제거](https://github.com/anifriends/frontend/commit/07dcd76048d296c2bc7149c46a99fec9b3458783)
=> feat(shelter): 봉사자 신청 현황 페이지 신청된 상태가 같을 경우 서버 호출 제거

apps/shelter/package.json, apps/volunteer/package.json, pnpm-lock.yaml
- close #334 
* [chore(shelter, volunteer): @lukemorales/query-key-factory 삭제](https://github.com/anifriends/frontend/commit/2d7b589fe54c4e8fc723e5b6fde22bab7e49da2c)
=> chore(shelter, volunteer): @lukemorales/query-key-factory 삭제

apps/shelter/src/mocks/handlers/manage.ts, apps/shelter/src/pages/manage/attendance/index.tsx
- close #336 
* [feat(shelter): 봉사자 출석 관리 페이지 관련 더미 데이터 개수 추가](https://github.com/anifriends/frontend/commit/453853eb93281bfe475ae0c37d77b2993c7cde0d)
* [feat(shelter): 봉사자 출석 관리 페이지 디자인 모바일에서 웹까지 확장](https://github.com/anifriends/frontend/commit/1e4edc5f742defa42bb77df84ff01fc9ace5d864)
=> feat: 봉사자 출석 관리 페이지 디자인 모바일에서 웹까지 확장

apps/shelter/src/App.tsx, apps/volunteer/src/App.tsx, packages/constants/src/baseURL.ts
- close #348 
* [fix(shelter, volunteer): queryOptions staleTime 숫자 식으로 수정](https://github.com/anifriends/frontend/commit/4174cef78a9f5ffeeb90d501d4876efcc511e9c2)
* [fix(package/constants): baseURL의 DEV_BASE_URL 수정](https://github.com/anifriends/frontend/commit/7ce4ba9f8013a288c7c210b8422f7dee2fdb76b8)
=> fix: queryOptions staleTime 숫자 식으로 변경, pacakages/constants의 baseURL DEV_BASE_URL 변경

apps/shelter/src/App.tsx, apps/volunteer/src/App.tsx, packages/constants/src/baseURL.ts
=> release: v0.1.12
